# Dev stage
FROM node:16 AS dev
WORKDIR /client
COPY ./client/package*.json ./

RUN mkdir node_modules && chown -R node:node /client
USER node
RUN npm install
COPY --chown=node:node ./client .

EXPOSE 5173

CMD ["npx", "vite", "--host"]


# Prod stage
FROM node:16 AS build
WORKDIR /client
COPY ./client/package*.json ./
RUN npm install
COPY ./client .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]