version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wift_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
